services:
  ngrok:
    image: ngrok/ngrok:3.16.0-alpine
    container_name: sapungobrol-ngrok
    restart: unless-stopped
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command:
      - http
      - http://host.docker.internal:8000
    ports:
      - 4040:4040

  db:
    image: postgres:16
    container_name: sapungobrol-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  db: