[tool.coverage.run]
source = ["."]
omit = ["db/__init__.py", "main.py"]

[tool.pytest.ini_options]
env = [
    "PORT=8000",
    "LOG_LEVEL=info",
    "DATABASE_URL=postgresql://postgres:postgres@localhost:5433",
]
