services:
  sapungobrol-stg:
    image: nayyaraairlangga/sapungobrol:latest
    container_name: sapungobrol-stg
    labels:
      caddy: sapungobrol.nairlangga.com
      caddy.reverse_proxy: "{{upstreams 8080}}"
    restart: unless-stopped
    env_file: .env
    environment:
      PORT: 8080
    networks:
      - public-web
      - sapungobrol-stg
  
  sapungobrol-db-stg:
    image: pgvector/pgvector:pg16
    container_name: sapungobrol-db-stg
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 10.243.242.62:5433:5432
    networks:
      - sapungobrol-stg
    volumes:
      - sapungobrol-db-stg:/var/lib/postgresql/data

  sapungobrol-promtail:
    image: grafana/promtail:3.0.1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - ./promtail-config.yml:/etc/promtail-config.yml:ro
    command: -config.file=/etc/promtail-config.yml
    ports:
      - "5140:5140"
    networks:
      - public-web
      - sapungobrol-stg

  .victorialogs:
    image: docker.io/victoriametrics/victoria-logs:v1.0.0-victorialogs
    command:
      - -storageDataPath=/vlogs
      - -loggerFormat=json
      - -syslog.listenAddr.tcp=0.0.0.0:8094
      - -journald.streamFields=_HOSTNAME,_SYSTEMD_UNIT,_PID
      - -journald.ignoreFields=MESSAGE_ID,INVOCATION_ID,USER_INVOCATION_ID,
      - -journald.ignoreFields=_BOOT_ID,_MACHINE_ID,_SYSTEMD_INVOCATION_ID,_STREAM_ID,_UID
    deploy:
      replicas: 0
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:9428/health"]
      interval: 1s
      timeout: 1s
      retries: 10
    networks:
      - public-web
      - sapungobrol-stg

  sapungobrol-victorialogs:
    extends: .victorialogs
    # ports:
    #   - '9428:9428'
    volumes:
      - victorialogs:/vlogs
    deploy:
      replicas: 1
    networks:
      - public-web

  sapungobrol-victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    # labels:
    #   caddy: sapungobrol.nairlangga.com
    #   caddy.reverse_proxy: "{{upstreams 8428}}"
    ports:
      - '8428:8428'
    command:
      - -storageDataPath=/vmsingle
      - -loggerFormat=json
    volumes:
      - victoriametrics:/vmsingle
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8428/health"]
      interval: 1s
      timeout: 1s
      retries: 10
    networks:
      - public-web
      - sapungobrol-stg

  sapungobrol-vmauth:
    image: docker.io/victoriametrics/vmauth:v1.106.1
    restart: on-failure
    # labels:
    #   caddy: sapungobrol.nairlangga.com
    #   caddy.reverse_proxy: "{{upstreams 9428}}"
    environment:
      USERNAME: ${VMAUTH_USERNAME}
      PASSWORD: ${VMAUTH_PASSWORD}
    volumes:
      - ./vmauth-config.yml:/etc/vmauth/vmauth-config.yml:ro
    command: -auth.config=/etc/vmauth/vmauth-config.yml
    networks:
      - public-web
      - sapungobrol-stg
    ports:
      - "9428:8427"

volumes:
  sapungobrol-db-stg:
    external: true
  victorialogs:
    external: true
  victoriametrics:
    external: true

networks:
  public-web:
    external: true
  sapungobrol-stg:
    external: true
